#!/bin/sh

log() {
  yellow="\e[0;33m"
  magenta="\e[0;35m"
  red="\e[0;31m"
  reset="\e[0;0m"
  printf "$magenta>$red>$yellow>$reset %s\n" "$*" 1>&2
}

init_submodules() {
  log "init submodules"
  yadm submodule update --recursive --init
}

setup_zsh() {
  log "setting Zsh as login shell"
  zsh=$(which zsh)
  sudo chsh -s "$zsh" $USER
}

install_packages() {
   sudo apt install xclip
   # sdkman
   curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh"
   sdk install kotlin kscript
}

setup_vim() {
  # make sure, vim is installed
  sudo apt install libxml2-utils vim vim-gtk
  mkdir -p "$XDG_DATA_HOME"/vim/{undo,swap,backup,view}
  vim +silent +PluginInstall +qall
}

# optional: not every machine is allowed to commit
update_yadm_url(){
  log "Updating the yadm repo origin URL"
  yadm remote set-url origin "git@github.com:gaerfield/dotfiles.git"
}

cd "$HOME"

init_submodules
setup_zsh
install_packages
setup_vim

