# explicitely set XDG-Directories
set -x XDG_CACHE_HOME $HOME/.cache
set -x XDG_CONFIG_HOME $HOME/.config
set -x XDG_LOCAL_HOME $HOME/.local
set -x XDG_PREFIX_HOME $XDG_LOCAL_HOME
set -x XDG_DATA_HOME $XDG_LOCAL_HOME/share
set -x XDG_STATE_HOME $XDG_LOCAL_HOME/state
set -x XDG_BIN_HOME $XDG_LOCAL_HOME/bin
set -x PATH $XDG_BIN_HOME:$PATH