set --global tide_aws_bg_color FF9900
set --global tide_aws_color 232F3E
set --global tide_bun_bg_color FBF0DF
set --global tide_bun_color 14151A
set --global tide_character_color 5FD700
set --global tide_character_color_failure FF0000
set --global tide_cmd_duration_bg_color C4A000
set --global tide_cmd_duration_color 000000
set --global tide_cmd_duration_decimals 0
set --global tide_cmd_duration_threshold 3000
set --global tide_context_always_display false
set --global tide_context_bg_color 444444
set --global tide_context_color_default D7AF87
set --global tide_context_color_root D7AF00
set --global tide_context_color_ssh D7AF87
set --global tide_context_hostname_parts 1
set --global tide_crystal_bg_color FFFFFF
set --global tide_crystal_color 000000
set --global tide_direnv_bg_color D7AF00
set --global tide_direnv_bg_color_denied FF0000
set --global tide_direnv_color 000000
set --global tide_direnv_color_denied 000000
set --global tide_distrobox_bg_color FF00FF
set --global tide_distrobox_color 000000
set --global tide_docker_bg_color 2496ED
set --global tide_docker_color 000000
set --global tide_docker_default_contexts default colima
set --global tide_elixir_bg_color 4E2A8E
set --global tide_elixir_color 000000
set --global tide_gcloud_bg_color 4285F4
set --global tide_gcloud_color 000000
set --global tide_git_bg_color 4E9A06
set --global tide_git_bg_color_unstable C4A000
set --global tide_git_bg_color_urgent CC0000
set --global tide_git_color_branch 000000
set --global tide_git_color_conflicted 000000
set --global tide_git_color_dirty 000000
set --global tide_git_color_operation 000000
set --global tide_git_color_staged 000000
set --global tide_git_color_stash 000000
set --global tide_git_color_untracked 000000
set --global tide_git_color_upstream 000000
set --global tide_git_truncation_length 24
set --global tide_git_truncation_strategy
set --global tide_go_bg_color 00ACD7
set --global tide_go_color 000000
set --global tide_java_bg_color ED8B00
set --global tide_java_color 000000
set --global tide_jobs_bg_color 444444
set --global tide_jobs_color 4E9A06
set --global tide_jobs_number_threshold 1000
set --global tide_kubectl_bg_color 326CE5
set --global tide_kubectl_color 000000
set --global tide_left_prompt_frame_enabled true
set --global tide_left_prompt_items vi_mode pwd git newline
set --global tide_left_prompt_prefix ''
set --global tide_left_prompt_separator_diff_color 
set --global tide_left_prompt_separator_same_color 
set --global tide_left_prompt_suffix 
set --global tide_nix_shell_bg_color 7EBAE4
set --global tide_nix_shell_color 000000
set --global tide_node_bg_color 44883E
set --global tide_node_color 000000
set --global tide_os_bg_color 35BF5C
set --global tide_os_color FFFFFF
set --global tide_php_bg_color 617CBE
set --global tide_php_color 000000
set --global tide_private_mode_bg_color F1F3F4
set --global tide_private_mode_color 000000
set --global tide_prompt_add_newline_before false
set --global tide_prompt_color_frame_and_connection 6C6C6C
set --global tide_prompt_color_separator_same_color 949494
set --global tide_prompt_min_cols 34
set --global tide_prompt_pad_items true
set --global tide_prompt_transient_enabled true
set --global tide_pulumi_bg_color F7BF2A
set --global tide_pulumi_color 000000
set --global tide_pwd_bg_color 3465A4
set --global tide_pwd_color_anchors E4E4E4
set --global tide_pwd_color_dirs E4E4E4
set --global tide_pwd_color_truncated_dirs BCBCBC
set --global tide_pwd_markers .bzr .citc .git .hg .node-version .python-version .ruby-version .shorten_folder_marker .svn .terraform Cargo.toml composer.json CVS go.mod package.json build.zig
set --global tide_python_bg_color 444444
set --global tide_python_color 00AFAF
set --global tide_right_prompt_frame_enabled true
set --global tide_right_prompt_items status cmd_duration context jobs direnv node python rustc java php pulumi ruby go gcloud kubectl distrobox toolbox terraform aws nix_shell crystal elixir zig
set --global tide_right_prompt_prefix 
set --global tide_right_prompt_separator_diff_color 
set --global tide_right_prompt_separator_same_color 
set --global tide_right_prompt_suffix ''
set --global tide_ruby_bg_color B31209
set --global tide_ruby_color 000000
set --global tide_rustc_bg_color F74C00
set --global tide_rustc_color 000000
set --global tide_shlvl_bg_color 808000
set --global tide_shlvl_color 000000
set --global tide_shlvl_threshold 1
set --global tide_status_bg_color 2E3436
set --global tide_status_bg_color_failure CC0000
set --global tide_status_color 4E9A06
set --global tide_status_color_failure FFFF00
set --global tide_terraform_bg_color 800080
set --global tide_terraform_color 000000
set --global tide_time_bg_color D3D7CF
set --global tide_time_color 000000
set --global tide_time_format %T
set --global tide_toolbox_bg_color 613583
set --global tide_toolbox_color 000000
set --global tide_vi_mode_bg_color_default 949494
set --global tide_vi_mode_bg_color_insert 87AFAF
set --global tide_vi_mode_bg_color_replace 87AF87
set --global tide_vi_mode_bg_color_visual FF8700
set --global tide_vi_mode_color_default 000000
set --global tide_vi_mode_color_insert 000000
set --global tide_vi_mode_color_replace 000000
set --global tide_vi_mode_color_visual 000000
set --global tide_zig_bg_color F7A41D
set --global tide_zig_color 000000
