#export FZF_MARKER_CONF_DIR=~/.config/marker
export FZF_MARKER_COMMAND_COLOR='\x1b[38;5;249m'
export FZF_MARKER_COMMENT_COLOR='\x1b[38;5;32m'
export FZF_MARKER_MAIN_KEY='\C-@'
export FZF_MARKER_PLACEHOLDER_KEY='\C-v'
