[".local/share/nvim/site/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".cache/zsh/zinit/bin"]
  type = "archive"
  url = "https://github.com/zdharma-continuum/zinit/archive/main.tar.gz"
  stripComponents = 1
  refreshPeriod = "168h"

