#
# User configuration sourced by interactive shells
#
export TERM="xterm-256color"
export DOTFILE_REPO="$HOME/.dotfiles"
export ZPLUG_REPO="$HOME/.zplug"

source ~/.fonts/*.sh

# zplug

export ZPLUG_LOADFILE="$DOTFILE_REPO/zsh/packages.zsh"
source $ZPLUG_REPO/init.zsh

if ! zplug check; then
    zplug install
fi

# use --verbose to list loaded plugins
zplug load --verbose

# theme-config
source $DOTFILE_REPO/zsh/theme.zsh
# keybindings
source $DOTFILE_REPO/zsh/keybindings.zsh
# fzf
source $DOTFILE_REPO/zsh/fzf.zsh

# Completions
# stolen from: https://github.com/Shougo/shougo-s-github/blob/64d1ff893c12439bb0bfdd30b7e48519f8b5711b/.zshrc

# Enable completions


# check zsh-options
# for example: https://github.com/Shougo/shougo-s-github/blob/64d1ff893c12439bb0bfdd30b7e48519f8b5711b/.zshrc

# Share zsh histories
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
setopt inc_append_history
setopt share_history
