#
# User configuration sourced by interactive shells
#
export TERM="xterm-256color"

source ~/.fonts/*.sh

# zplug
export ZPLUG_LOADFILE="${ZDOTDIR:-$HOME}/.dotfiles/zsh/packages.zsh"
source ~/.zplug/init.zsh

if ! zplug check; then
    zplug install
fi

# use --verbose to list loaded plugins
zplug load

# theme-config
source ~/.dotfiles/zsh/theme.zsh
# keybindings
source ~/.dotfiles/zsh/keybindings.zsh


# Completions
# stolen from: https://github.com/Shougo/shougo-s-github/blob/64d1ff893c12439bb0bfdd30b7e48519f8b5711b/.zshrc

# Enable completions


# check zsh-options
# for example: https://github.com/Shougo/shougo-s-github/blob/64d1ff893c12439bb0bfdd30b7e48519f8b5711b/.zshrc

# Share zsh histories
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
setopt inc_append_history
setopt share_history

# bringt das was?
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
