#
# User configuration sourced by interactive shells
#
export TERM="xterm-256color"
export DOTFILE_REPO="$HOME/.dotfiles"
export ZPLUG_REPO="$HOME/.zplug"

source ~/.fonts/*.sh

# zplug

export ZPLUG_LOADFILE="$DOTFILE_REPO/zsh/packages.zsh"
source $ZPLUG_REPO/init.zsh

if ! zplug check; then
    zplug install
fi

# use --verbose to list loaded plugins
zplug load #--verbose

# powerlevel9k-Konfiguration
source $DOTFILE_REPO/zsh/theme.zsh
# Wort vor- und zurück springen
source $DOTFILE_REPO/zsh/keybindings.zsh
# Alias
source $DOTFILE_REPO/zsh/alias.zsh
# Auto-Completion
source $DOTFILE_REPO/zsh/completions.zsh
# History-Einstellungen etc.
source $DOTFILE_REPO/zsh/options.zsh
# fuzzy-search/completions etc.
source $DOTFILE_REPO/zsh/fzf.zsh
