#!/bin/sh

log() {
  yellow="\e[0;33m"
  magenta="\e[0;35m"
  red="\e[0;31m"
  reset="\e[0;0m"
  printf "$magenta>$red>$yellow>$reset %s\n" "$*" 1>&2
}

init_submodules() {
  log "init submodules"
  yadm submodule update --recursive --init
}

update_yadm_url(){
  log "Updating the yadm repo origin URL"
  yadm remote set-url origin "git@github.com:gaerfield/dotfiles.git"
}

setup_zsh() {
  log "setting Zsh as login shell"
  zsh=$(which zsh)
  sudo chsh -s "$zsh" $USER
}

install_pet() {
  log "installing pet console snippet-manager"
  url='https://github.com/knqyf263/pet/releases/download/v0.3.2/pet_0.3.2_linux_amd64.deb'
  TEMP_DEB=$(mktemp)
  curl -o $TEMP_DEB -L $url
  sudo dpkg -i $TEMP_DEB
  rm -f $TEMP_DEB
}

cd "$HOME"

init_submodules
update_yadm_url
setup_zsh
install_pet

